### PR TITLE
Don't reload on initialize. Fixes #87

### LINKED ISSUE #87: Revert Reload on #new
So in using ActiveTriples::Resources as "Almost ActiveRecord" objects, the only big difference I found was that because they reload on #new, there's no such thing as a record with a URI in the database that's not persisted, which makes things like #new forms difficult.

We ended up writing https://github.com/OregonDigital/ControlledVocabularyManager/blob/feature/ActiveTermWrapper/lib/active_triples_adapter.rb

Should we push this kind of behavior into the AT API for a new major version?

### PR DESCRIPTION
**Pull request by jcoyne**

### CODE REVIEW

**Comment by jcoyne** [comment]
I think this will still require `(node? && self.class.repository != :parent) ` because we're going to set some values on the new node and we don't want it to attempt loading then either.

**Comment by jcoyne** [comment]
@no-reply I never got feedback on this. Should I rebase it against 0.8.1? This was the alternate implementation of #111

**Comment by no-reply** [comment]
@jcoyne yeah. This is good, it just got held due to the major refactors that were incoming. If you rebase, I think we can move forward.

I have a question about the philosophy of `#loaded?`. Is/should `#loaded?` be equivalent to a `#current?`; or is there an argument for keeping `#loaded?` and `#persisted?` separate?

@terrellt and I have had discussions about introducing an `RDFSourceBuilder` or other creational pattern. So there may be some churn following this; fair warning.

**Comment by jcoyne** [comment]
Closing this PR to do a PR against the v0.7 branch.

**Pull request closed without merging**
