### PR TITLE
valid? should run activemodel validations. Fixes #145

### LINKED ISSUE #145: regression in behavior of valid?
With ActiveTriples 0.6 valid? was provided by ActiveModel::Validations, in 0.7 it's provided by RDF::Mixin::Enumerable

### PR DESCRIPTION
**Pull request by jcoyne**

### CODE REVIEW

**Comment by jcoyne** [comment]
I think this also needs a forward-port to master/develop. I think that 0.8.0 may only be running the RDF::Enumerable#valid?

**Comment by no-reply** [comment]
@jcoyne can you explain what's going on here?

**Comment by jcoyne** [comment]
@no-reply the `valid?` method is defined by `RDF::Enumerable` and by `ActiveModel::Validations`.  This commit makes sure that the code for both is run when you call `ActiveTriples::RDFSource#valid?`

**Comment by jcoyne** [comment]
What's the status here?

**Comment by jcoyne** [comment]
Hello? Anybody home?

**Pull request merged**
