### PR TITLE
Moved include of ActiveModel::Validations inside included block of RDFSource

### LINKED ISSUE #166: Validations are broken
At least in AT 0.7.1, validation callbacks are not run.  See https://github.com/dchandekstark/ActiveTriples/blob/validations-bug/spec/active_triples/validations_spec.rb.

### PR DESCRIPTION
**Pull request by dchandekstark**
Added tests of validations.

Fixes #166

Should fix projecthydra/active_fedora#914 and projecthydra/active_fedora#915, so would like to request a bugfix release ASAP if the PR is accepted.

### CODE REVIEW

**Comment by mjgiarlo** [comment]
:+1:

**Comment by dchandekstark** [comment]
@no-reply @tpendragon @jcoyne Please take a look, thanks.

**Comment by jcoyne** [comment]
:+1:

**Comment by no-reply** [comment]
I'm pulling this down and looking at how it interacts with 0.8 work, but looks good.

**Comment by dchandekstark** [comment]
Amended to backport `validate` block from 0.8.

**Comment by no-reply** [comment]
Coveralls isn't happy about the test coverage for validations. I'm inclined to merge over its objections. The appropriate tests are in https://github.com/ActiveTriples/ActiveTriples/commit/a0a013c4b088b4de6a43c57b4e7ed0822c438fa5#diff-bb6c3706c078b897a420b0606cd93270R185, but I'm not sure I see much point in backporting them.

**Pull request merged**
