### PR TITLE
Add Coveralls badge and Fury gem version badge to README

### PR DESCRIPTION
**Pull request by elrayle**

### CODE REVIEW

**Comment by no-reply** [comment]
Cool :sunglasses:.

**Comment by no-reply** [comment]
98% :interrobang: 

I guess that's pretty good.

**Comment by elrayle** [comment]
My minter gem comes in at 79%, which makes it a very unsatisfying red icon. I believe this is due to the fact that the gem is so small.  There aren't any obvious omissions in the test suite.  

98% and green is very satisfying.

**Comment by terrellt** [comment]
https://coveralls.io/files/418771304#L54 I blame @jcoyne

**Comment by no-reply** [comment]
I blame @no-reply.

**Pull request merged**
