### PR TITLE
Raise an error when a missing repository is encountered

### PR DESCRIPTION
**Pull request by jcoyne**

### CODE REVIEW

**Comment by no-reply** [comment]
I don't have time to give this a ton of thought right now, but I wonder what people think about introducing a logger? 

What are the implications if this just raises an error, instead?

**Comment by jcoyne** [comment]
@no-reply Yeah, I'm having second thoughts about this. Shouldn't this case always be an error?

**Comment by jcoyne** [comment]
@no-reply Okay, now it's an error.

**Comment by no-reply** [comment]
Can someone (@terrellt?) do a sanity check on the changes around L262 (https://github.com/ActiveTriples/ActiveTriples/pull/85/files#diff-da5e93b351d7fa394bc8d7723aa95313L262)?  

I'm not immediately parsing the `final_parent` logic and won't likely have time to look closer in the next few days.  I'm :+1: if someone else can do a quick review.

**Comment by terrellt** [comment]
Sanity checked. :+1:

**Pull request merged**
