### PR TITLE
Children should not be persisted? unless their parents are. Fixes #148

### LINKED ISSUE #148: When using parent strategy a new object should not be persisted if the parent isn't
regression introduced in  710ebd5178aec9a88ad57ae1b77b4cd1db41f5ac

### PR DESCRIPTION
**Pull request by jcoyne**

### CODE REVIEW

**Comment by no-reply** [comment]
With the exception of the question about the integration tests, I'm :+1: on this.

**Comment by terrellt** [comment]
I'm +0. It seems like a different definition of `persisted?`, but things are in such a state now that maybe this is the step forward. I'm worried about things which check to see if the RDFSource is persisted, but tests seem fine.

**Comment by jcoyne** [comment]
@terrellt this isn't a new feature. It's a fix to a regression that is preventing existing software from running.

**Comment by jcoyne** [comment]
@no-reply The integration test doesn't expand the coverage at all, but it shows why the unit tests must behave the way they do. It also works without mocking anything.  Where would you like it stashed? `spec/integration` ?

**Comment by no-reply** [comment]
`spec/integration` sounds good.

**Comment by no-reply** [comment]
@jcoyne :+1: to this fixing the regression. 

I agree with @terrellt that this might eventually change back (I think this change was made deliberately), but we really need to nail things down on `ParentStrategy` more generally, first.

**Pull request merged**
