### PR TITLE
Removes odd logic surrounding property clearance

### PR DESCRIPTION
**Pull request by no-reply**
In cases where a class with registered RDF type was deleted from a relation, the value would be retained when using `Relation#set`. This removes those conditionals and adds a regression test.

### CODE REVIEW

**Comment by no-reply** [comment]
This deals with one issue documented in #154.

**Comment by jcoyne** [comment]
I think the reason this existed is because some people (BPL I think?) had a use case where two properties were defined that shared a predicate but had a different class_name. E.g.:

```ruby
property :widgets, predicate: OpaqueNS.hasPart, class_name: 'Widget'
property :sprockets, predicate: OpaqueNS.hasPart, class_name: 'Sprocket'
```
then when you set `#widgets=` you didn't want it to wipe out your `#sprockets`

**Comment by jcoyne** [comment]
See https://github.com/projecthydra/active_fedora/commit/de9b7ed5d52461d314ccc22b440c0d701feb1a2d

/cc @scande3

**Comment by jcoyne** [comment]
In proto-ActiveTriples land this originated with this commit: https://github.com/projecthydra/active_fedora/commit/3a50d14c99402dd8a658bd30837a71336e740a53

Given the example it looks like it would affect WGBH, so ping @afred

**Comment by no-reply** [comment]
> I think the reason this existed is because some people (BPL I think?) had a use case where two properties were defined that shared a predicate but had a different class_name.

OregonDigital certainly had this use case, too. My feeling is that this pattern has repeatedly bitten us.

The core problem is that we have never had a clear `Relation` semantics. Setters behave in one way; getters in another. Both are subject to unexpected behavior when using `rdf:type` as anything other than a model specifier, or when you try to inherit types.

I'm okay if we want to explore ways to retain this behavior, but I think we need to spec out a really clear approach, if so.

**Comment by mjsuhonos** [comment]
This has potential implications for `#<<` semantics too, eg. for above:

```ruby
my_object << [subject_uri, OpaqueNS.hasPart, some_object]
```

Would presumably have to do some introspection on `some_object` to determine which property (`#widgets` or `#sprockets`) is being modified (not to mention exception raising for incorrect classes; are we already doing this?).

I can also imagine some implications for persistence, depending on how the strategy is implemented; ie. whether it's property-based or predicate-based.

**Comment by jcoyne** [comment]
@mjsuhonos I don't see that being affected, because you've dropped down a level at that point. You are using the RDF API not the ActiveTriples API so you wouldn't expect any of the AT rules to exist there.  Frankly I understand why this is a gross hairy issue, I just want the institutions affected to accept that we will be removing a feature they depend on.

**Comment by no-reply** [comment]
@mjsuhonos bingo. Things get really fun if you do.

```ruby
obj.widgets = Sprocket.new
# or
obj.widgets = [Sprocket.new, Widget.new, 'blah', Sprokget.new]
```

**Comment by jcoyne** [comment]
Also, removing this feature probably breaks nested attributes (when you have two properties that share a class_name)

**Comment by no-reply** [comment]
@jcoyne can you write a test for the crucial nested attribute features?

Nested attributes really needs a strong advocate, here. I've never really understood them or how they can be used effectively for RDF.

**Comment by mjsuhonos** [comment]
>> You are using the RDF API not the ActiveTriples API so you wouldn't expect any of the AT rules to exist there.

@jcoyne Gah, of course you're right. The respective AT getters are where the logic is. I don't have a strong opinion on this since I can work with it either way.

**Comment by no-reply** [comment]
>  I just want the institutions affected to accept that we will be removing a feature they depend on.

:+1:. I also want to make sure there's a clean way to do the thing they want.

Moving to an approach with one-to-one property-predicate mapping would really simplify things, and I would hope that it gives us a solid foundation for other access patterns.

But yeah, it's a hairy issue. I've been trying to get my head around this for about a year now, and as you can see, progress is slow. Strong opinions on how things *should* work really help.

**Comment by escowles** [comment]
A one-to-one property-predicate mapping seems like a good idea to me.  Additional functionality can be added on top of that to inspect the values and do different things with different kinds of values.  If that's not good enough, you can always create a sub-predicate for the special cases and use that for a separate property.

**Comment by mjsuhonos** [comment]
:+1: simplest case first.

**Comment by jcoyne** [comment]
@mjsuhonos I would agree but for the ship having already sailed. Making the change now will impose a  rather large upgrade burden.

**Comment by scande3** [comment]
Not using ActiveFedora 9, it is hard to comment since I don't know what is being changed. I don't believe this affects us there is only one "property" per object association. As best to reference jcoyne's comment, I can provide what we do in ActiveFedora 8:

In ObjectBase (which is inherited by more complex object representations), we have the following:

    has_many :exemplary_image, :class_name => "Bplmodels::File", :property=> :is_exemplary_image_of

    has_many :image_files, :class_name => "Bplmodels::ImageFile", :property=> :is_image_of

    has_many :audio_files, :class_name => "Bplmodels::AudioFile", :property=> :is_audio_of

    has_many :document_files, :class_name => "Bplmodels::DocumentFile", :property=> :is_document_of

    has_many :files, :class_name => "Bplmodels::File", :property=> :is_file_of

Due to the inheritance casting commit that was referenced, our ":is_file_of" property (or predicate in more modern terms) can reference objects of type File, DocumentFile, AudioFile, etc. However, as you can see above, more specific access cases use their own separate property (or predicate) rather than relying on the class to limit it.

Hopefully that makes sense? But as far as I can tell with limited understanding of this commit and no testing on our models, this particular commit doesn't affect us since we don't use the same property twice just with a different class.

**Pull request merged**
