### PR TITLE
Don't reload b-nodes from the remote repository

### LINKED ISSUE #87: Revert Reload on #new
So in using ActiveTriples::Resources as "Almost ActiveRecord" objects, the only big difference I found was that because they reload on #new, there's no such thing as a record with a URI in the database that's not persisted, which makes things like #new forms difficult.

We ended up writing https://github.com/OregonDigital/ControlledVocabularyManager/blob/feature/ActiveTermWrapper/lib/active_triples_adapter.rb

Should we push this kind of behavior into the AT API for a new major version?

### PR DESCRIPTION
**Pull request by jcoyne**
Fixes #87

### CODE REVIEW

**Comment by no-reply** [comment]
I don't think this closes #87.

I'm generally in favor of this, as an improvement to bnode handling. #110 pointed out that the existing bnode handling breaks on certain `Repository` implementations--it's not clear to me whether that's a problem with AT or the repositories, but I do think that *some* bnodes can't be identified to be reloaded.  Starting at not trying to identify ones without parents may be a good starting place.

I want to take a closer look, and would encourage others to do the same, with the idea of getting this merged in the next couple of days unless there's an issue.

**Comment by terrellt** [comment]
This is a tough one. I think #87 and allowing the repository to error on #find is a better way to handle this.

**Comment by no-reply** [comment]
> allowing the repository to error on #find is a better way to handle this.

You mean handling the error and passing on? This sounds smart.  Some repositories (in memory ones with the Graph directly projected?) actually may respond just fine to requests like this.  Then again, these queries are probably too expensive to be something that is going to routinely fail.

Maybe there's an interface in `Repository` that can help us here? Or one we can write into persistence strategies?

**Comment by gkellogg** [comment]
The best way to handle this generically would be to have a skolemizing repository, so that the BNodes could be replaced with Skolemized IRIs; that would allow you to retrieve and manipulate them. Otherwise, accessing such nodes can only be done indirectly. Ultimately, RDF::Enumerable would need to support something like a `:skolemize` with a means of returning a new enumerable with BNodes replaced by Skolem IDs. Because the namespace for Skolem IDs is application specific, it can't really be done generically. If this is important, consider issuing a PR against RDF.rb.

**Comment by jcoyne** [comment]
I think #87 largely solves my problem. It was only on `new` that I was having trouble with this. I'm cool with withdrawing this.

**Comment by no-reply** [comment]
@jcoyne, okay.  I think that buys us some time to think more seriously about it, as long as someone can take on the issue of figuring out a better initialization/reload pattern.

@gkellogg Skolemizing seems be a behavior option we would want to give, but I'd be reluctant to impose it.  Some of our adopters use systems that do their own skolemization, and I'd also want AT to play nice with systems that write bnodes on a shared Repository.

**Comment by jcoyne** [comment]
@no-reply should I move my conditional out of reload and into `initialize`

**Comment by no-reply** [comment]
@jcoyne no, I think we should remove `#reload` from `#initialize` altogether.

**Comment by gkellogg** [comment]
@no-reply The `:skolemize` feature would just say that a repo supports skolemization, and that there is a mechanism to get to the version of the repo which uses skolemn IDs instead of BNodes, it wouldn't impose anything. If an adapter does skolemization, this would just be a way to access it. I created https://github.com/ruby-rdf/rdf/issues/172 on RDF.rb as a feature request. This would be a good place to gather requirements and comments.

**Comment by no-reply** [comment]
@gkellogg :+1: :rocket: :fireworks:

**Pull request closed without merging**
