### PR TITLE
Feature/relation cleanup

### PR DESCRIPTION
**Pull request by no-reply**

### CODE REVIEW

**Comment by elrayle** [comment]
I am concerned about the removal of #delete and #[]= 

How would you change a single value or delete a single value?  If I interpret the impact correctly, if you have a property with a large number of values (100k), you have to manipulate all of them as a unit.

Code that no longer works...
```
      subject.aggregates = orig_bib1
      subject.aggregates << orig_bib2
      subject.aggregates << orig_bib3

      subject.aggregates[0] = new_bib1
      subject.aggregates[2] = new_bib3
```

**Comment by jcoyne** [comment]
I don't think that `#[]=` is well defined over an unordered set.

**Comment by no-reply** [comment]
As @jcoyne points out, `#[]=` is undefined. Currently, its behavior depends on the backing `RDF::Repository`. For the default in-memory repository, access is stable in the `1.x` release series; in `2.x` using `#[]=` as implemented will result in deletion of a random value. This is also true of most other repositories.

I'm happy to reintroduce `#delete`. It was unused internally and entirely untested, so it seemed like a good idea to simply remove it and see who balked. Still, it seems nice to have it. Adapting @elrayle's example:

```ruby
subject.aggregates = orig_bib1
subject.aggregates << orig_bib2
subject.aggregates << orig_bib3

subject.aggregates.delete(orig_bib1)
subject.aggregates << new_bib1
subject.aggregates.delete(orig_bib3)
subject.aggregates << new_bib3
```

I'll re-add it and test.

**Comment by elrayle** [comment]
That works for me. Thanks.

**Comment by tpendragon** [comment]
:+1: to delete. Relation is a poor Set without it.

**Comment by no-reply** [comment]
@elrayle & @tpendragon thanks. `#delete` is back and better than ever, with tests and docs and everything.

**Comment by no-reply** [comment]
Per discussion on slack, with naming suggestion from @cbeer, added `#swap`.

Additionally, added `#delete?` as a more expensive, but more informative version of `#delete`.

**Comment by elrayle** [comment]
This looks good to me.  If I don't here any other comments by 2:00 ET, I'll merge this.

**Comment by elrayle** [comment]
@mjsuhonos @no-reply Does this address issue #198?

**Pull request merged**
