### PR TITLE
Refactor/rename Resource to RDFSource Mixin

### PR DESCRIPTION
**Pull request by no-reply**
This replaces `Resource` with a mixin module, `RDFSource` and renames `Term` to `Relation` (which is the word used in most RDF documentation for the analogous concept).

I think this refactor makes significant improvements to the general object structure, and opens the door to improvements like those being explored in ActiveTriples/feature/persistence-strategies

Review and testing is desired. cc: @terrellt, @jcoyne, @elrayle, @jeremyf, @mjsuhonos

### CODE REVIEW

**Comment by no-reply** [comment]
Some previous discussion exists on #98.

**Comment by no-reply** [comment]
I took a peek at `Mongoid::Document` for a reference on how they handle initialization for the mixin class.  They go ahead and define `#initialize`.

My inclination is toward a builder class with the initializer available through `Resource`.

**Comment by no-reply** [comment]
@jcoyne mentioned that it would be a good idea to deprecate `Term`.  I'll make that change.

**Comment by no-reply** [comment]
The latest commit deprecates `Term`, but it's worth noting that...

```ruby
my_resource.property.is_a? Term
``` 
...will be false.

**Comment by no-reply** [comment]
Barring objections, I plan to merge this as is.  Work is progressing on `PersistenceStrategy` and other refactorings & interface clarifications that depend on this.

cc: @jcoyne @terrellt @jeremyf @dchandekstark @mjsuhonos

**Comment by no-reply** [comment]
I'm expecting to add a commit to update the REAME to cover some of the conceptual content of this comment: https://github.com/ActiveTriples/ActiveTriples/issues/117#issuecomment-94557079

**Comment by no-reply** [comment]
This now removes support for Ruby 1.9.3.  Everything should still work, except the dependency issue documented here: https://github.com/ruby-rdf/linkeddata/issues/6 But it seems to make sense to drop support in future versions, since 1.9.3 itself is no longer supported. Complaints?

**Comment by terrellt** [comment]
> Complaints?

Nope, dropping 1.9 is a good thing at this point.

**Comment by mjsuhonos** [comment]
:clap:

**Pull request merged**
