### PR TITLE
Added the ability to define a language on get_values.

### LINKED ISSUE #17: Language Handling
It should be possible to handle languages in Resource#get_values. Probably, RDF::Literals should be returned with their lang tag intact.

### PR DESCRIPTION
**Pull request by jcoyne**
A port of
https://github.com/projecthydra/active_fedora/commit/cdc4d778f60965978dd56a2ee36f2c2df280595d
Fixes #17

### CODE REVIEW

**Comment by no-reply** [comment]
This looks good to me. :+1:

**Comment by terrellt** [comment]
The reason I didn't port this before was because there's a way to get literals out now and handle the filtering at the application layer. Is querying for language at the AT layer something we want?

**Comment by jcoyne** [comment]
@terrellt Without it, this code won't work: https://github.com/OregonDigital/oregondigital/blob/577399213c34bf6cc83458d3abcc9112540d98bf/lib/oregon_digital/rdf/controlled.rb#L60-L62

That seems like a common scenario.

**Comment by terrellt** [comment]
@jcoyne That's true - my point is I think that's bad code (that I wrote). I could replace it by doing

```ruby 
values = get_values(label, :literal => true)
[:en, :"en-us"].each do |preferred_language|
  result = values.select{|x| x.language == preferred_language}
  unless result.blank?
    break
  end
end
result = values if result.blank?
```
Or something less miserable and hacky, but you get the idea.

**Comment by terrellt** [comment]
I guess my point is I don't think we should build in the ability to filter values at the accessor level when it's just as easy to filter after the fact.

**Comment by jcoyne** [comment]
Had a conversation on IRC:

@jcoyne said:
```
values_with_language(:en)
```

@no-reply said:
```
something like that
or `values.with_language(:en)`
or even `values.where(:language => :en)`
```

**Comment by terrellt** [comment]
Sure, #where works for me. It's not a big difference from basic array manipulation, but it reads a bit better.

**Comment by no-reply** [comment]
From a conversation with @terrellt: 

tom:
> i'm actually starting to think `Term/Relation` should just have a `#where` method that returns a query object against the values.
> e.g. `my_resource.property.where.language(:en)`
> or `my_resource.property.where.type(RDF::OWL.Thing)`

@terrellt:
> Just watch for the "how do I query deep" use case.

tom:
> it should chain fine, as long as you have a sense of how best to filter out literals
>`my_resource.property.where.type(RDF::OWL.Thing).each { |thing| thing.name.where.language(:en) }`
> could probably come up with something to prettify the common `#each` call
and nuke any literal values

**Comment by no-reply** [comment]
Closing this as long stale. Even if we wanted this now, porting forward would be more substantial than a rebase.

**Pull request closed without merging**
